#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d I II III IV V
bspc monitor HDMI-1 -d  VI VII VIII IX 
bspc config border_width         5
bspc config window_gap           6
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
feh --bg-fill --randomize ~/imgs/wallpaper/* &
~/.config/polybar/./launch.sh --forest &
alacritty &
xrandr --output eDP-1 --brightness 1.3 &
sudo /home/ivanse/.config/bspwm/setb.sh 1.1 &
systemctl --user enable --now ulauncher.service &
systemctl start iwd &
# iwctl --passphrase rr29261522 station wlan0 connect Tao5 &
# iwctl --passphrase 0146628794 station wlan0 connect "Fibertel WiFi033 5.8Ghz" &
# iwctl --passphrase 4464794 station wlan0 connect "Speedy-juan123"
iwctl --passphrase 28364429 station wlan0 connect "sanmartin1"
neofetch &
